[ContentBrowser]
ContentBrowserTab1.SelectedPaths=/Game/ThirdPersonCPP

[/Script/Blutility.EditorUtilitySubsystem]

#ToolMenu scripts to run on startup
#Menu Object for the Main Menu
+StartupObjects=/Game/CouchGame2025/Widget/EUM_MyMenu.EUM_MyMenu
+StartupObjects=/Game/CouchGame2025/Widget/EUM_MySubMenu.EUM_MySubMenu